### ISSUE TITLE
Lots of deprecation warnings when running bench task

### ISSUE THREAD

**Issue by vizvamitra** [jeremyevans/r10k#4]
I'm getting tons of warnings when running `bundle exec rake bench`. I don't think this is a real issue since everything is still working, just wanted to notify about it.

Here are the warnings:

> DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is 'text/plain'. (called from g at /home/.../r10k/apps/rails_4_10.rb:32004)`

and

> DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:
>
>  "Rack::Lock" => Rack::Lock
>
> (called from <top (required)> at /home/.../r10k/apps/rails_4_10.rb:32016)

ruby 2.3.1
rack 2.0.1
rails 5.0.0.1

**Comment by jeremyevans** [comment]
I'm guessing those deprecation warnings are new in Rails 5.  I agree they should be fixed, I'll work on that shortly.
